create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime(6), status integer, total double precision, primary key (id)) engine=InnoDB;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=InnoDB;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime(6), status integer, total double precision, primary key (id)) engine=InnoDB;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=InnoDB;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime(6), status integer, total double precision, primary key (id)) engine=InnoDB;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=InnoDB;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime(6), status integer, total double precision, primary key (id)) engine=InnoDB;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=InnoDB;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime(6), status integer, total double precision, primary key (id)) engine=InnoDB;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=InnoDB;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime(6), status integer, total double precision, primary key (id)) engine=InnoDB;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=InnoDB;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime(6), status integer, total double precision, primary key (id)) engine=InnoDB;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=InnoDB;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime(6), status integer, total double precision, primary key (id)) engine=InnoDB;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=InnoDB;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime(6), status integer, total double precision, primary key (id)) engine=InnoDB;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=InnoDB;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime, status integer, total double precision, primary key (id)) engine=MyISAM;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=MyISAM;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=MyISAM;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime, status integer, total double precision, primary key (id)) engine=MyISAM;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=MyISAM;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=MyISAM;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime, status integer, total double precision, primary key (id)) engine=MyISAM;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=MyISAM;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=MyISAM;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime, status integer, total double precision, primary key (id)) engine=MyISAM;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=MyISAM;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=MyISAM;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime, status integer, total double precision, primary key (id)) engine=MyISAM;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=MyISAM;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=MyISAM;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
create table pedido (id bigint not null auto_increment, endereco varchar(255), latitude double precision, longitude double precision, momento datetime, status integer, total double precision, primary key (id)) engine=MyISAM;
create table pedido_produto (pedido_id bigint not null, produto_id bigint not null, primary key (pedido_id, produto_id)) engine=MyISAM;
create table produto (id bigint not null auto_increment, descricao varchar(255), imagem_uri varchar(255), nome varchar(255), preco double precision, primary key (id)) engine=MyISAM;
alter table pedido_produto add constraint FKf8l3k06bmjhdwd79t0ndcw7tt foreign key (produto_id) references produto (id);
alter table pedido_produto add constraint FKcsbxw0y9i3wfmiupq9eqfpdtc foreign key (pedido_id) references pedido (id);
